# Generated by Django 6.0.5 on 2026-05-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
